services:
  perplexica:
    image: digi4care/perplexica-search-engine-ai:latest
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - data:/home/vane/data
    restart: unless-stopped

volumes:
  data:
    name: 'perplexica-data'