FROM node:24.5.0-slim AS builder

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/digi4care

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps --network-timeout 600000

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY drizzle ./drizzle

RUN mkdir -p /home/digi4care/data
RUN npm run build

FROM node:24.5.0-slim

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/digi4care

COPY --from=builder /home/digi4care/public ./public
COPY --from=builder /home/digi4care/.next/static ./public/_next/static

COPY --from=builder /home/digi4care/.next/standalone ./
COPY --from=builder /home/digi4care/data ./data
COPY drizzle ./drizzle

RUN mkdir /home/digi4care/uploads

RUN npm install playwright
RUN npx playwright install --with-deps --only-shell chromium

EXPOSE 3000

CMD ["node", "server.js"]
